name: build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true

      - name: Get version
        id: get_version
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }} Build ${{ steps.get_version.outputs.VERSION }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          
